reindent main

diff --git a/vimmerge b/vimmerge
--- a/vimmerge
+++ b/vimmerge
@@ -10,7 +10,7 @@
 #   2. 2-way merge with output to a new file
 #   3. 3-way merge with output to "mine"
 #   4. 3-way merge with output to a new file
-#   5. 2-way merge with all input coming from one file, 
+#   5. 2-way merge with all input coming from one file,
 #      which uses markup similar to the output of RCS merge.
 #      In this case, only a single input file is given on the cmdline.
 #
@@ -33,95 +33,94 @@
 #   vimmerge -w merged conflicted
 
 main() {
+  cmd=${0%merge}
+  cmd=${cmd##*/}
+  unset mine older yours write order
+  backup=false
+  unset backup_mv_flags
+  quiet=false
 
-cmd=${0%merge}
-cmd=${cmd##*/}
-unset mine older yours write order
-backup=false
-unset backup_mv_flags
-quiet=false
+  args=$(getopt -o m:y:o:w:bq --long mine:,yours:,older:,write:,quiet,backup -n "$0" -- "$@") || exit
+  eval set -- "$args"
 
-args=$(getopt -o m:y:o:w:bq --long mine:,yours:,older:,write:,quiet,backup -n "$0" -- "$@") || exit
-eval set -- "$args"
-
-while true; do
+  while true; do
     case $1 in
-        -b|--backup) backup=true; shift ;;
-        -m|--mine)  mine=$2; shift 2 ;;
-        -o|--older) older=$2; shift 2 ;;
-        -y|--yours) yours=$2; shift 2 ;;
-        -w|--write) write=$2; shift 2 ;;
-        --order) order=$2; shift 2 ;;
-        -q|--quiet) quiet=true; shift ;;
-        --) shift; break ;;
-        *) echo "failed to process cmdline args" >&2; exit 1 ;;
+      -b|--backup) backup=true; shift ;;
+      -m|--mine)  mine=$2; shift 2 ;;
+      -o|--older) older=$2; shift 2 ;;
+      -y|--yours) yours=$2; shift 2 ;;
+      -w|--write) write=$2; shift 2 ;;
+      --order) order=$2; shift 2 ;;
+      -q|--quiet) quiet=true; shift ;;
+      --) shift; break ;;
+      *) echo "failed to process cmdline args" >&2; exit 1 ;;
     esac
-done
+  done
 
-# This --order hack is for programs that expect a certain command-line order and
-# aren't configurable
-if [[ -z $order ]]; then
+  # This --order hack is for programs that expect a certain command-line order and
+  # aren't configurable
+  if [[ -z $order ]]; then
     # if order isn't specified, assume the same order as diff3
     [[ -z $mine ]] && { mine=$1; shift; }
     [[ -z $older && -n $2 ]] && { older=$1; shift; }
     [[ -z $yours ]] && { yours=$1; shift; }
-else
+  else
     while [[ -n $order ]]; do
-        o=${order:0:1}
-        order=${order:1}
-        case $o in
-            m) [[ -z $mine ]] && { mine=$1; shift; } ;;
-            o) [[ -z $older ]] && { older=$1; shift; } ;;
-            y) [[ -z $yours ]] && { yours=$1; shift; } ;;
-            w) [[ -z $write ]] && { write=$1; shift; } ;;
-            *) echo "error: valid --order chars are moyw" >&2; exit 1 ;;
-        esac
+      o=${order:0:1}
+      order=${order:1}
+      case $o in
+        m) [[ -z $mine ]] && { mine=$1; shift; } ;;
+        o) [[ -z $older ]] && { older=$1; shift; } ;;
+        y) [[ -z $yours ]] && { yours=$1; shift; } ;;
+        w) [[ -z $write ]] && { write=$1; shift; } ;;
+        *) echo "error: valid --order chars are moyw" >&2; exit 1 ;;
+      esac
     done
-fi
+  fi
 
-if [[ -z $mine ]]; then
+  if [[ -z $mine ]]; then
     echo "syntax: ${cmd}merge [options] mine [[older] yours]" >&2
     exit 1
-fi
+  fi
 
-# Default output file is $mine
-: ${write:=$mine}
+  # Default output file is $mine
+  : ${write:=$mine}
 
-# 3-way and RCS merge require temporary files
-if [[ -z $yours || -n $older ]]; then
+  # 3-way and RCS merge require temporary files
+  if [[ -z $yours || -n $older ]]; then
     unset tmp_mine tmp_yours
     trap 'rm -f "$tmp_mine" "$tmp_yours"' 0 1 2 15
     tmp_mine=$(mktemp -t mine.XXXXXX) || exit 1
     tmp_yours=$(mktemp -t conflicts.XXXXXX) || exit 1
-fi
+  fi
 
-if [[ -z $yours ]]; then
+  if [[ -z $yours ]]; then
     # Process the results of RCS merge
     sed -n "
-        /^<<<<<<< /,/^>>>>>>> /{
-            /^<<<<<<< /,/^=======\$/{
-                /^<<<<<<< /d    # skip the start marker
-                /^=======\$/!{  # skip the end marker
-                    w $tmp_mine
-                }
-            }
-            /^=======\$/,/^>>>>>>> /{
-                /^=======\$/d   # skip the start marker
-                /^>>>>>>> /!{   # skip the end marker
-                    w $tmp_yours
-                }
-            }
-            d
+      /^<<<<<<< /,/^>>>>>>> /{
+        /^<<<<<<< /,/^=======\$/{
+          /^<<<<<<< /d    # skip the start marker
+          /^=======\$/!{  # skip the end marker
+            w $tmp_mine
+          }
         }
-        w $tmp_mine
-        w $tmp_yours" < "$mine" || exit 1
+        /^=======\$/,/^>>>>>>> /{
+          /^=======\$/d   # skip the start marker
+          /^>>>>>>> /!{   # skip the end marker
+            w $tmp_yours
+          }
+        }
+        d
+      }
+      w $tmp_mine
+      w $tmp_yours" < "$mine" || exit 1
     yours="$tmp_yours"
     mine="$tmp_mine"
     # falls through to 2-way merge
-fi
+  fi
 
-# 3-way merge
-if [[ -n $older ]]; then
+  # 3-way merge
+  if [[ -n $older ]]; then
     unset tmp_mine tmp_yours
 
     trap 'rm -f "$tmp_mine" "$tmp_yours"' 0 1 2 15
@@ -136,42 +135,41 @@ if [[ -n $older ]]; then
 
     # was the simple merge fully successful?
     if cmp --quiet "$tmp_mine" "$tmp_yours"; then
-        $backup && backup_mv_flags="--backup=simple --suffix=.orig"
-        mv $backup_mv_flags "$tmp_mine" "$write" || exit 1
-        $quiet || echo "Simple merge successful ($write)"
-        exit 0
+      $backup && backup_mv_flags="--backup=simple --suffix=.orig"
+      mv $backup_mv_flags "$tmp_mine" "$write" || exit 1
+      $quiet || echo "Simple merge successful ($write)"
+      exit 0
     fi
 
     # call vim to complete the merge
     if $backup && [[ -f "$write" ]]; then
-        mv -f "$write" "$write.orig" || exit 1
+      mv -f "$write" "$write.orig" || exit 1
     fi
     $cmd -f +diffthis +"topleft vert new $write" +"0r $tmp_mine" +diffthis "$tmp_yours"
     exit 0
-fi
+  fi
 
-# 2-way merge
-if cmp --quiet "$mine" "$yours"; then
+  # 2-way merge
+  if cmp --quiet "$mine" "$yours"; then
     $quiet || echo "Files are identical"
     exit 0
-elif [[ $write == "$mine" ]]; then
+  elif [[ $write == "$mine" ]]; then
     if $backup && [[ -f "$mine" ]]; then
-        cp -f "$mine" "$mine.orig" || exit 1
+      cp -f "$mine" "$mine.orig" || exit 1
     fi
     $cmd -f -d "$mine" "$yours"
     exit $?
-else
+  else
     if [[ -f "$write" ]] && $backup; then
-        mv -f "$write" "$write.orig" || exit 1
+      mv -f "$write" "$write.orig" || exit 1
     fi
     $cmd -f +diffthis +"topleft vert new $write" +"normal dG" +"r $mine" +"normal kdd" +diffthis "$yours"
     status=$?
     if [[ ! -f "$write" ]] && $backup; then
-        mv -f "$write.orig" "$write" || exit 1
+      mv -f "$write.orig" "$write" || exit 1
     fi
     exit $status
-fi
-
+  fi
 } # end of main
 
 ###############################################################################
@@ -238,7 +236,7 @@ getopt() {
         (-h|--help)
           _getopt_help
           return 2  # as does GNU getopt
-          ;; 
+          ;;
 
         (-l|--longoptions)
           long="$long${long:+,}$2"
@@ -556,7 +554,7 @@ getopt() {
         return 2 ;;
       (1)
         printf '%s' "$matches"; return 0 ;;
-      (*) 
+      (*)
         [[ $flags == *q* ]] || \
         printf "$name: option %s is ambiguous; possibilities: %s\n" >&2 \
           "$(_getopt_quote "$q")" "$(_getopt_quote "${matches[@]}")"
@@ -603,12 +601,12 @@ getopt() {
 
   _getopt_help() {
     cat <<-EOT >&2
-	
+
 	Usage:
 	 getopt optstring parameters
 	 getopt [options] [--] optstring parameters
 	 getopt [options] -o|--options optstring [options] [--] parameters
-	
+
 	Options:
 	 -a, --alternative            Allow long options starting with single -
 	 -h, --help                   This small usage guide
@@ -621,7 +619,7 @@ getopt() {
 	 -T, --test                   Test for getopt(1) version
 	 -u, --unquote                Do not quote the output
 	 -V, --version                Output version information
-	
+
 	EOT
   }
 
